# CI de Nível 03 - Diaparo apos a conclusao de um pipeline

# nome do nosso  nosso pipeline

name: 'Execução por deploy'

# regras de disparo (gatilhos/triggers)
# gatilho de exec manual = workflow_dispatch
# gatilho de exec agendado = schedule
# gatilho do exec a partir de outro pipe = workflow_run

on:

  workflow_run:
  workflows: ['Execução Manual']
  types: 
    -completed

# trabalhos/tarefas dentro do pipeline = jobs
jobs:
  e2e-tests: 
    #maquina que o job vai executar
    runs-on: ubuntu-latest

    # passos do script de build
    steps:
      #  clone do projeto
      - uses: actions/checkout@v4

      # instalação do node
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      # instalação do yarn
      - name: Instalando Yarn
        run: npm install -g yarn

      # instalação das dependências
      - name: Instalando depedências
        run: yarn


      # instalação do Playwright
      - name: Instalando Playwright
        run: yarn playwright install


      # executar os testes e2e
      - name: Executando teste E2E
        run: yarn run e2e



  